### ISSUE TITLE
Using uni-data-table causes EntryPointNotFoundException

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter.Uniform#17]
Using 2.1.0 of this library causes following exception:

```
System.EntryPointNotFoundException: Entry point was not found.
   at System.IDisposable.Dispose()
   at Starcounter.Uniform.Queryables.FilteredPaginatedDataProvider`2.DisposeOfRows() in C:\Users\joozek\dev\starcounter.uniform\Starcounter.Uniform\Queryables\FilteredPaginatedDataProvider.cs:line 93
   at Starcounter.Uniform.Queryables.FilteredPaginatedDataProvider`2.get_CurrentPageRows() in C:\Users\joozek\dev\starcounter.uniform\Starcounter.Uniform\Queryables\FilteredPaginatedDataProvider.cs:line 55
   at Starcounter.Uniform.ViewModels.UniDataTable.LoadRows() in C:\Users\joozek\dev\starcounter.uniform\Starcounter.Uniform\ViewModels\UniDataTable.json.cs:line 51
```

It's thrown, because 2.1.0 was built with wrong version of Starcounter

**Comment by joozek78** [comment]
Resolved in 2.1.1
