### ISSUE TITLE
Ignore diacritics when searching

### ISSUE THREAD

**Issue by alshakero** [Starcounter/Starcounter.Uniform#19]
I think it makes sense to ignore diacritics when searching. Currently, typing Gekas doesn't yeild any Gekås results. 

I think we need to use something of the lines of [this](https://stackoverflow.com/questions/359827/ignoring-accented-letters-in-string-comparison):

```csharp
string.Compare(s1, s2, CultureInfo.CurrentCulture, CompareOptions.IgnoreNonSpace);
```

**Comment by warpech** [comment]
I think this should be provided in user code, not hardcoded in the library. However, the library should have a handy way of providing such configuration/callback function. 

@PatrykSzwer can you please make sure that it is possible and that there is an example of that in the docs, as well as the sample implementation in UniformDocs uses it?

**Comment by PatrykSzwer** [comment]
I thought about adding such a feature to the `.Filterable()` method, so it would be another `bool` argument to it. So it would look like:
```
this.DataTable = new DataTableBuilder<DataTableRow>()
                .WithDataSource(DbLinq.Objects<Person>(), data => data.WithConverter(CreateDataTableRow))
                .WithColumns(columns =>
                    columns
                        .AddColumn(b => b.FirstName, column => column.DisplayName("First Name").Sortable().Filterable(ignoreDiacritics:true))
```
WDYT about such solution?

**Comment by PatrykSzwer** [comment]
I could add a feature as an argument to the `.Filterable()` method, but I think its possible right now to do it trough custom filter. I'll propose implementation for it.

**Comment by PatrykSzwer** [comment]
After short talk with Marcin we agreed to update current example of filter implementation with the `string.Compare` method to ignore diacritics. Updated example can be found here: https://github.com/Starcounter/Starcounter.Uniform#computed-columns

Closing as done.

**Comment by PatrykSzwer** [comment]
I'm afraid that I have to reopen this issue, since we forgot about one small detail about our LINQ... :
```
System.NotSupportedException: Method call is not supported
	   at Starcounter.Linq.Visitors.WhereVisitor`1.VisitMethodCall(MethodCallExpression node, QueryBuilder`1 state)
	   at Starcounter.Linq.Visitors.WhereVisitor`1.VisitBinaryEquality(Expression left, Expression right, QueryBuilder`1 state, Boolean isEqualsSign)
	   at Starcounter.Linq.Visitors.WhereVisitor`1.VisitBinary(BinaryExpression node, QueryBuilder`1 state)
	   at Starcounter.Linq.Visitors.RootVisitor`1.VisitWhere(Expression expression, QueryBuilder`1 state)
	   at Starcounter.Linq.Visitors.RootVisitor`1.VisitMethodCall(MethodCallExpression node, QueryBuilder`1 state)
	   at Starcounter.Linq.Visitors.RootVisitor`1.VisitMethodCall(MethodCallExpression node, QueryBuilder`1 state)
	   at Starcounter.Linq.QueryContext`1.Execute[TResult](Expression expression)
	   at Starcounter.Linq.QueryProvider.System.Linq.IQueryProvider.Execute[T](Expression expression)
	   at Starcounter.Linq.Queryable`1.GetEnumerator()
	   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

```

Progress on that can be followed here: https://github.com/Starcounter/Starcounter.Linq/issues/79

**Comment by PatrykSzwer** [comment]
I added a solution to the readme, suggested by @un-tone here: https://github.com/Starcounter/Starcounter.Linq/issues/79#issuecomment-483232278

Closing as done.

**Comment by warpech** [comment]
Could you please add it to the data table page in UniformDocs?

**Comment by PatrykSzwer** [comment]
I added example implementation to the pr https://github.com/Starcounter/UniformDocs/pull/400 since it contains an implementation of custom filter.

**Comment by miyconst** [comment]
Copying my answer from [Can't call string.Compare method in the query](https://github.com/Starcounter/Starcounter.Linq/issues/79#issuecomment-487473584):

--------

@PatrykSzwer, @un-tone, @warpech, I don't think this is a proper solution for the problem.

Calling `.ToList` on an `IQueriable` will execute the SQL query and lift **all** rows from the database into CLR. Every further filtering will happen in CLR.

The string filtering is way more efficient on the database level, if an index can be utilized. Lifting filtering to the CLR level, removes the index usage possibility.

The diacritics behavior shall be controlled by the database collation settings, unfortunately, currently there is no way to have different collation for different tables / columns, only per database.

Still, filtering can be done on the database level with usage of a computed property. For example:

```cs
using System;
using System.Text;
using System.Globalization;

[Database]
public class Book
{
    public string Name { get; set; }

    public string NameFiltrable
    {
        get
        {
            string normalizedString = this.Name.Normalize(NormalizationForm.FormD);
            StringBuilder sb = new StringBuilder();

            foreach (char c in normalizedString)
            {
                UnicodeCategory unicodeCategory = CharUnicodeInfo.GetUnicodeCategory(c);

                if (unicodeCategory != UnicodeCategory.NonSpacingMark)
                {
                    sb.Append(c);
                }
            }

            string result = sb.ToString().Normalize(NormalizationForm.FormC);

            return result;
        }
    }
}
```

Even though we currently don't support indexes over computed properties, this have the following benefits:

- Does not lift all rows with `FETCH X` queries.
- We plan to provide support for indexing over computed properties.
- All follow up filters can be executed on the database side as well.
- The computed property can always be replaced with a real property, which will copy the main value without diacritics for indexing and performance.

----------

*P.S. The provided solution is shamelessly copied from:*

- [stackoverflow.com: How do I remove diacritics (accents) from a string in .NET?](https://stackoverflow.com/questions/249087/how-do-i-remove-diacritics-accents-from-a-string-in-net)
- [archives.miloush.net: Stripping diacritics....](http://archives.miloush.net/michkap/archive/2005/02/19/376617.html)
